
package reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTOA;

import reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.*;
import reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.utils.*;
import reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class AccionDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	
	/* Rol: Accion o--> UsuarioWeb */
	private UsuarioWebDTOA usuarioAccion;
	public UsuarioWebDTOA getUsuarioAccion () { return usuarioAccion; }
	public void setUsuarioAccion (UsuarioWebDTOA usuarioAccion) { this.usuarioAccion = usuarioAccion; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public AccionDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			
			

			JSONObject jsonUsuarioAccion = json.optJSONObject("UsuarioAccion");
			if (jsonUsuarioAccion != null)
			{
				UsuarioWebDTOA tmp = new UsuarioWebDTOA();
				tmp.setFromJSON(jsonUsuarioAccion);
				this.usuarioAccion = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
			

			if (this.usuarioAccion != null)
			{
				json.put("UsuarioAccion", this.usuarioAccion.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		AccionDTO dto = new AccionDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
		
		
		// Roles
					// TODO: from DTOA [ UsuarioAccion ] (dataType : UsuarioWebDTOA) to DTO [ Usuario ]
		
		
		return dto;
	}

	// endregion
}

	