
package reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTOA;

import reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.*;
import reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.utils.*;
import reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class NotaInformativaDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String titulo;
	public String getTitulo () { return titulo; }
	public void setTitulo (String titulo) { this.titulo = titulo; }
	
	private String cuerpo;
	public String getCuerpo () { return cuerpo; }
	public void setCuerpo (String cuerpo) { this.cuerpo = cuerpo; }
	
	private java.util.Date fecha;
	public java.util.Date getFecha () { return fecha; }
	public void setFecha (java.util.Date fecha) { this.fecha = fecha; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public NotaInformativaDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Titulo")))
			{
			 
				this.titulo = (String) json.opt("Titulo");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Cuerpo")))
			{
			 
				this.cuerpo = (String) json.opt("Cuerpo");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Fecha")))
			{
			 
			 	String stringDate = (String) json.opt("Fecha");
				this.fecha = DateUtils.stringToDateFormat(stringDate);
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.titulo != null)
			json.put("Titulo", this.titulo);
		
		
		  if (this.cuerpo != null)
			json.put("Cuerpo", this.cuerpo);
		
		
		  if (this.fecha != null)
			json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		NotaInformativaDTO dto = new NotaInformativaDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setTitulo (this.getTitulo());

	dto.setCuerpo (this.getCuerpo());

	dto.setFecha (this.getFecha());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	