
package reciclaUAGenReciclaUARESTAzure.uiModels.DTOA;

import reciclaUAGenReciclaUARESTAzure.uiModels.DTO.*;
import reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
import reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class MaterialDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String nombre;
	public String getNombre () { return nombre; }
	public void setNombre (String nombre) { this.nombre = nombre; }
	
	private TipoContenedor contenedor;
	public TipoContenedor getContenedor () { return contenedor; }
	public void setContenedor (TipoContenedor contenedor) { this.contenedor = contenedor; }
	
	private Estado esValido;
	public Estado getEsValido () { return esValido; }
	public void setEsValido (Estado esValido) { this.esValido = esValido; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public MaterialDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Nombre")))
			{
			 
				this.nombre = (String) json.opt("Nombre");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Contenedor")))
			{
				int enumRawValue = (int) json.opt("Contenedor");
				this.contenedor = TipoContenedor.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("EsValido")))
			{
				int enumRawValue = (int) json.opt("EsValido");
				this.esValido = Estado.fromRawValue(enumRawValue);
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.nombre != null)
			json.put("Nombre", this.nombre);
		
		
		  if (this.contenedor != null)
			json.put("Contenedor", this.contenedor.getRawValue());
		
		
		  if (this.esValido != null)
			json.put("EsValido", this.esValido.getRawValue());
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		MaterialDTO dto = new MaterialDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setNombre (this.getNombre());

	dto.setContenedor (this.getContenedor());

	dto.setEsValido (this.getEsValido());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	