	
		//
		// AccionDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class AccionDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var usuario_oid: Int?;
				    	 
		 
				var fecha: NSDate?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["usuario_oid"] = self.usuario_oid;
			

				
					dictionary["fecha"] = self.fecha?.toString();
				
						
				return dictionary;
			}
		}
		
	