	
		//
		// AccionReciclarDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class AccionReciclarDTO :    		AccionDTO
	    {
		 
				var contenedor_oid: Int?;
				    	 
		 
				var item_oid: Int?;
				    	 
		 
				var cantidad: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


					dictionary["contenedor_oid"] = self.contenedor_oid;
			

					dictionary["item_oid"] = self.item_oid;
			

				
					dictionary["cantidad"] = self.cantidad;
				
						
				return dictionary;
			}
		}
		
	