	
		//
		// NotaInformativaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class NotaInformativaDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var usuarioAdministrador_oid: Int?;
				    	 
		 
				var titulo: String?;
				    	 
		 
				var cuerpo: String?;
				    	 
		 
				var fecha: NSDate?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["usuarioAdministrador_oid"] = self.usuarioAdministrador_oid;
			

				
					dictionary["titulo"] = self.titulo;
				

				
					dictionary["cuerpo"] = self.cuerpo;
				

				
					dictionary["fecha"] = self.fecha?.toString();
				
						
				return dictionary;
			}
		}
		
	