	
		//
		// PlantaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class PlantaDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var planta: Planta?;
				    	 
		 
				var estancias_oid: [String]?;
				    	 
		 
				var edificio_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["planta"] = self.planta?.rawValue;
				

					dictionary["estancias_oid"] = self.estancias_oid;
			

					dictionary["edificio_oid"] = self.edificio_oid;
			
						
				return dictionary;
			}
		}
		
	