	
		//
		// PuntoReciclajeDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class PuntoReciclajeDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var latitud: Double?;
				    	 
		 
				var longitud: Double?;
				    	 
		 
				var esValido: Estado?;
				    	 
		 
				var usuario_oid: Int?;
				    	 
		 
				var contenedores: [ContenedorDTO]?;
				    	 
		 
				var estancia_oid: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["latitud"] = self.latitud;
				

				
					dictionary["longitud"] = self.longitud;
				

				
					dictionary["esValido"] = self.esValido?.rawValue;
				

					dictionary["usuario_oid"] = self.usuario_oid;
			

					dictionary["contenedores"] = NSNull();
					if (self.contenedores != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.contenedores!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["contenedores"] = arrayOfDictionary;
					}
			

					dictionary["estancia_oid"] = self.estancia_oid;
			
						
				return dictionary;
			}
		}
		
	