	
		//
		// RespuestaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class RespuestaDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var cuerpo: String?;
				    	 
		 
				var duda_oid: Int?;
				    	 
		 
				var usuario_oid: Int?;
				    	 
		 
				var fecha: NSDate?;
				    	 
		 
				var esCorrecta: Bool?;
				    	 
		 
				var util: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["cuerpo"] = self.cuerpo;
				

					dictionary["duda_oid"] = self.duda_oid;
			

					dictionary["usuario_oid"] = self.usuario_oid;
			

				
					dictionary["fecha"] = self.fecha?.toString();
				

				
					dictionary["esCorrecta"] = self.esCorrecta;
				

				
					dictionary["util"] = self.util;
				
						
				return dictionary;
			}
		}
		
	