	
		package reciclaUAGenReciclaUARESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class AccionReciclarDTO extends    		AccionDTO
	    implements IDTO
	    {
				private Integer contenedor_oid;
				public Integer  getContenedor_oid () { return contenedor_oid; } 
				public void setContenedor_oid (Integer value) { contenedor_oid = value;  } 
				    	 
				private Integer item_oid;
				public Integer  getItem_oid () { return item_oid; } 
				public void setItem_oid (Integer value) { item_oid = value;  } 
				    	 
				private Integer cantidad;
				public Integer getCantidad () { return cantidad; } 
				public void setCantidad  (Integer value) { cantidad = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.contenedor_oid != null)
						{
							json.put("Contenedor_oid", this.contenedor_oid.intValue());
						}

						if (this.item_oid != null)
						{
							json.put("Item_oid", this.item_oid.intValue());
						}
				
						  json.put("Cantidad", this.cantidad.intValue());
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	