	
		package reciclaUAGenReciclaUARESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class ContenedorDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private TipoContenedor tipo;
				public TipoContenedor getTipo () { return tipo; } 
				public void setTipo  (TipoContenedor value) { tipo = value;  } 
				    	 
				private Integer punto_oid;
				public Integer  getPunto_oid () { return punto_oid; } 
				public void setPunto_oid (Integer value) { punto_oid = value;  } 
				    	 
				private ArrayList<Integer> acciones_oid;
				public ArrayList<Integer>  getAcciones_oid () { return acciones_oid; } 
				public void setAcciones_oid (ArrayList<Integer> value) { acciones_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Tipo", this.tipo.getRawValue());
				

						if (this.punto_oid != null)
						{
							json.put("Punto_oid", this.punto_oid.intValue());
						}

						if (this.acciones_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.acciones_oid.size(); ++i)
							{
								jsonArray.put(this.acciones_oid.get(i));
							}
							json.put("Acciones_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	