	
		package reciclaUAGenReciclaUARESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class EdificioDTO 	    implements IDTO
	    {
				private String nombre;
				public String getNombre () { return nombre; } 
				public void setNombre  (String value) { nombre = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private ArrayList<String> estancias_oid;
				public ArrayList<String>  getEstancias_oid () { return estancias_oid; } 
				public void setEstancias_oid (ArrayList<String> value) { estancias_oid = value;  } 
				    	 
				private ArrayList<Integer> plantas_oid;
				public ArrayList<Integer>  getPlantas_oid () { return plantas_oid; } 
				public void setPlantas_oid (ArrayList<Integer> value) { plantas_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Nombre", this.nombre);
				
				
						  json.put("Id", this.id.intValue());
				

						if (this.estancias_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.estancias_oid.size(); ++i)
							{
								jsonArray.put(this.estancias_oid.get(i));
							}
							json.put("Estancias_oid", jsonArray);
						}
		

						if (this.plantas_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.plantas_oid.size(); ++i)
							{
								jsonArray.put(this.plantas_oid.get(i));
							}
							json.put("Plantas_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	