	
		package reciclaUAGenReciclaUARESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class ItemDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String nombre;
				public String getNombre () { return nombre; } 
				public void setNombre  (String value) { nombre = value;  } 
				    	 
				private String descripcion;
				public String getDescripcion () { return descripcion; } 
				public void setDescripcion  (String value) { descripcion = value;  } 
				    	 
				private String imagen;
				public String getImagen () { return imagen; } 
				public void setImagen  (String value) { imagen = value;  } 
				    	 
				private Estado esValido;
				public Estado getEsValido () { return esValido; } 
				public void setEsValido  (Estado value) { esValido = value;  } 
				    	 
				private Integer usuario_oid;
				public Integer  getUsuario_oid () { return usuario_oid; } 
				public void setUsuario_oid (Integer value) { usuario_oid = value;  } 
				    	 
				private Integer nivel_oid;
				public Integer  getNivel_oid () { return nivel_oid; } 
				public void setNivel_oid (Integer value) { nivel_oid = value;  } 
				    	 
				private Integer material_oid;
				public Integer  getMaterial_oid () { return material_oid; } 
				public void setMaterial_oid (Integer value) { material_oid = value;  } 
				    	 
				private ArrayList<Integer> accionReciclar_oid;
				public ArrayList<Integer>  getAccionReciclar_oid () { return accionReciclar_oid; } 
				public void setAccionReciclar_oid (ArrayList<Integer> value) { accionReciclar_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Nombre", this.nombre);
				
				
						  json.put("Descripcion", this.descripcion);
				
				
						  json.put("Imagen", this.imagen);
				
				
						  json.put("EsValido", this.esValido.getRawValue());
				

						if (this.usuario_oid != null)
						{
							json.put("Usuario_oid", this.usuario_oid.intValue());
						}

						if (this.nivel_oid != null)
						{
							json.put("Nivel_oid", this.nivel_oid.intValue());
						}

						if (this.material_oid != null)
						{
							json.put("Material_oid", this.material_oid.intValue());
						}

						if (this.accionReciclar_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.accionReciclar_oid.size(); ++i)
							{
								jsonArray.put(this.accionReciclar_oid.get(i));
							}
							json.put("AccionReciclar_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	