	
		package reciclaUAGenReciclaUARESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class JuegoDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Integer itemActual;
				public Integer getItemActual () { return itemActual; } 
				public void setItemActual  (Integer value) { itemActual = value;  } 
				    	 
				private Integer aciertos;
				public Integer getAciertos () { return aciertos; } 
				public void setAciertos  (Integer value) { aciertos = value;  } 
				    	 
				private Integer fallos;
				public Integer getFallos () { return fallos; } 
				public void setFallos  (Integer value) { fallos = value;  } 
				    	 
				private Double puntuacion;
				public Double getPuntuacion () { return puntuacion; } 
				public void setPuntuacion  (Double value) { puntuacion = value;  } 
				    	 
				private ArrayList<Integer> usuarios_oid;
				public ArrayList<Integer>  getUsuarios_oid () { return usuarios_oid; } 
				public void setUsuarios_oid (ArrayList<Integer> value) { usuarios_oid = value;  } 
				    	 
				private Integer intentosItemActual;
				public Integer getIntentosItemActual () { return intentosItemActual; } 
				public void setIntentosItemActual  (Integer value) { intentosItemActual = value;  } 
				    	 
				private Boolean finalizado;
				public Boolean getFinalizado () { return finalizado; } 
				public void setFinalizado  (Boolean value) { finalizado = value;  } 
				    	 
				private Integer nivelActual;
				public Integer getNivelActual () { return nivelActual; } 
				public void setNivelActual  (Integer value) { nivelActual = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("ItemActual", this.itemActual.intValue());
				
				
						  json.put("Aciertos", this.aciertos.intValue());
				
				
						  json.put("Fallos", this.fallos.intValue());
				
				
						  json.put("Puntuacion", this.puntuacion);
				

						if (this.usuarios_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.usuarios_oid.size(); ++i)
							{
								jsonArray.put(this.usuarios_oid.get(i));
							}
							json.put("Usuarios_oid", jsonArray);
						}
		
				
						  json.put("IntentosItemActual", this.intentosItemActual.intValue());
				
				
						  json.put("Finalizado", this.finalizado);
				
				
						  json.put("NivelActual", this.nivelActual.intValue());
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	