	
		package reciclaUAGenReciclaUARESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class PlantaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Planta planta;
				public Planta getPlanta () { return planta; } 
				public void setPlanta  (Planta value) { planta = value;  } 
				    	 
				private ArrayList<String> estancias_oid;
				public ArrayList<String>  getEstancias_oid () { return estancias_oid; } 
				public void setEstancias_oid (ArrayList<String> value) { estancias_oid = value;  } 
				    	 
				private Integer edificio_oid;
				public Integer  getEdificio_oid () { return edificio_oid; } 
				public void setEdificio_oid (Integer value) { edificio_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Planta", this.planta.getRawValue());
				

						if (this.estancias_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.estancias_oid.size(); ++i)
							{
								jsonArray.put(this.estancias_oid.get(i));
							}
							json.put("Estancias_oid", jsonArray);
						}
		

						if (this.edificio_oid != null)
						{
							json.put("Edificio_oid", this.edificio_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	