	
		package reciclaUAGenReciclaUARESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class RespuestaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String cuerpo;
				public String getCuerpo () { return cuerpo; } 
				public void setCuerpo  (String value) { cuerpo = value;  } 
				    	 
				private Integer duda_oid;
				public Integer  getDuda_oid () { return duda_oid; } 
				public void setDuda_oid (Integer value) { duda_oid = value;  } 
				    	 
				private Integer usuario_oid;
				public Integer  getUsuario_oid () { return usuario_oid; } 
				public void setUsuario_oid (Integer value) { usuario_oid = value;  } 
				    	 
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
				private Boolean esCorrecta;
				public Boolean getEsCorrecta () { return esCorrecta; } 
				public void setEsCorrecta  (Boolean value) { esCorrecta = value;  } 
				    	 
				private Integer util;
				public Integer getUtil () { return util; } 
				public void setUtil  (Integer value) { util = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Cuerpo", this.cuerpo);
				

						if (this.duda_oid != null)
						{
							json.put("Duda_oid", this.duda_oid.intValue());
						}

						if (this.usuario_oid != null)
						{
							json.put("Usuario_oid", this.usuario_oid.intValue());
						}
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				
				
						  json.put("EsCorrecta", this.esCorrecta);
				
				
						  json.put("Util", this.util.intValue());
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	