	
		package reciclaUAGenReciclaUARESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUARESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class UsuarioWebDTO extends    		UsuarioDTO
	    implements IDTO
	    {
				private ArrayList<AccionDTO> acciones;
				public ArrayList<AccionDTO> getAcciones () { return acciones; } 
				public void setAcciones (ArrayList<AccionDTO> value) { acciones = value;  } 
				    	 
				private Integer puntuacion;
				public Integer getPuntuacion () { return puntuacion; } 
				public void setPuntuacion  (Integer value) { puntuacion = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.acciones != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.acciones.size(); ++i)
							{
								jsonArray.put(this.acciones.get(i).toJSON());
							}
							json.put("Acciones", jsonArray);
						}
				
						  json.put("Puntuacion", this.puntuacion.intValue());
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	