//
// EdificioDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class EdificioDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var nombre: String?;
	
	/* Rol: Edificio o--> Planta */
	var plantasEdicio: [PlantaDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.nombre = json["Nombre"].object as? String;
		
		if (json["PlantasEdicio"] != JSON.null)
		{
			self.plantasEdicio = [];
			for subJson in json["PlantasEdicio"].arrayValue
			{
				self.plantasEdicio!.append(PlantaDTOA(fromJSONObject: subJson));
			}
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Nombre"] = self.nombre;
	
	
		
		dictionary["PlantasEdicio"] = NSNull();
		if (self.plantasEdicio != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.plantasEdicio!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["PlantasEdicio"] = arrayOfDictionary;
		}

		
		
		return dictionary;
	}
}

	