//
// JuegoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class JuegoDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var itemActual: Int?;
	var aciertos: Int?;
	var fallos: Int?;
	var puntuacion: Double?;
	var intentosItemActual: Int?;
	var finalizado: Bool?;
	var nivelActual: Int?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.itemActual = json["ItemActual"].object as? Int;
		self.aciertos = json["Aciertos"].object as? Int;
		self.fallos = json["Fallos"].object as? Int;
		self.puntuacion = json["Puntuacion"].object as? Double;
		self.intentosItemActual = json["IntentosItemActual"].object as? Int;
		self.finalizado = json["Finalizado"].object as? Bool;
		self.nivelActual = json["NivelActual"].object as? Int;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["ItemActual"] = self.itemActual;
	
	

	
		dictionary["Aciertos"] = self.aciertos;
	
	

	
		dictionary["Fallos"] = self.fallos;
	
	

	
		dictionary["Puntuacion"] = self.puntuacion;
	
	

	
		dictionary["IntentosItemActual"] = self.intentosItemActual;
	
	

	
		dictionary["Finalizado"] = self.finalizado;
	
	

	
		dictionary["NivelActual"] = self.nivelActual;
	
	
		
		
		
		return dictionary;
	}
}

	