//
// AccionDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class AccionDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	
	/* Rol: Accion o--> UsuarioWeb */
	var usuarioAccion: UsuarioWebDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		
		if (json["UsuarioAccion"] != JSON.null)
		{
			self.usuarioAccion = UsuarioWebDTOA(fromJSONObject: json["UsuarioAccion"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	
		
		dictionary["UsuarioAccion"] = self.usuarioAccion?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	