//
// DudaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class DudaDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var titulo: String?;
	var cuerpo: String?;
	var fecha: NSDate?;
	var util: Int?;
	var tema: Tema?;
	
	/* Rol: Duda o--> UsuarioAdminAutenticado */
	var usuarioDuda: UsuarioAdminAutenticadoDTOA?;

	
	/* ServiceLink: obtenerNumeroDeRespuestas */
	var obtenerNumeroDeRespuestas: Int?;

	/* ServiceLink: obtenerSiRespuestaValida */
	var obtenerSiRespuestaValida: Bool?;

	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.titulo = json["Titulo"].object as? String;
		self.cuerpo = json["Cuerpo"].object as? String;
	
		self.fecha = NSDate.initFromString(json["Fecha"].object as? String);
		self.util = json["Util"].object as? Int;
		if let enumValue = json["Tema"].object as? Int
		{
			self.tema = Tema(rawValue: enumValue);
		}
		
		if (json["UsuarioDuda"] != JSON.null)
		{
			self.usuarioDuda = UsuarioAdminAutenticadoDTOA(fromJSONObject: json["UsuarioDuda"]);
		}

		
		if (json["ObtenerNumeroDeRespuestas"] != JSON.null)
		{
			self.obtenerNumeroDeRespuestas = DudaDTOA(fromJSONObject: json["ObtenerNumeroDeRespuestas"]);
		}
		if (json["ObtenerSiRespuestaValida"] != JSON.null)
		{
			self.obtenerSiRespuestaValida = DudaDTOA(fromJSONObject: json["ObtenerSiRespuestaValida"]);
		}
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Titulo"] = self.titulo;
	
	

	
		dictionary["Cuerpo"] = self.cuerpo;
	
	

	
		dictionary["Fecha"] = self.fecha?.toString();
	
	

	
		dictionary["Util"] = self.util;
	
	

	
		dictionary["Tema"] = self.tema?.rawValue;
	
	
		
		dictionary["UsuarioDuda"] = self.usuarioDuda?.toDictionary() ?? NSNull();

		
		dictionary["ObtenerNumeroDeRespuestas"] = self.obtenerNumeroDeRespuestas?.toDictionary() ?? NSNull();
		dictionary["ObtenerSiRespuestaValida"] = self.obtenerSiRespuestaValida?.toDictionary() ?? NSNull();
		
		return dictionary;
	}
}

	