//
// EstanciaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class EstanciaDTOA : DTOA
{
	// MARK: - Properties

	var id: String?;
	
	var actividad: String?;
	var latitud: Double?;
	var longitud: Double?;
	var nombre: String?;
	
	/* Rol: Estancia o--> Edificio */
	var edificioEstancia: EdificioDTOA?;

	/* Rol: Estancia o--> Planta */
	var plantaEstancia: PlantaDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? String
		
	
		self.actividad = json["Actividad"].object as? String;
		self.latitud = json["Latitud"].object as? Double;
		self.longitud = json["Longitud"].object as? Double;
		self.nombre = json["Nombre"].object as? String;
		
		if (json["EdificioEstancia"] != JSON.null)
		{
			self.edificioEstancia = EdificioDTOA(fromJSONObject: json["EdificioEstancia"]);
		}

		if (json["PlantaEstancia"] != JSON.null)
		{
			self.plantaEstancia = PlantaDTOA(fromJSONObject: json["PlantaEstancia"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Actividad"] = self.actividad;
	
	

	
		dictionary["Latitud"] = self.latitud;
	
	

	
		dictionary["Longitud"] = self.longitud;
	
	

	
		dictionary["Nombre"] = self.nombre;
	
	
		
		dictionary["EdificioEstancia"] = self.edificioEstancia?.toDictionary() ?? NSNull();

		dictionary["PlantaEstancia"] = self.plantaEstancia?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	