//
// NotaInformativaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class NotaInformativaDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var titulo: String?;
	var cuerpo: String?;
	var fecha: NSDate?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.titulo = json["Titulo"].object as? String;
		self.cuerpo = json["Cuerpo"].object as? String;
	
		self.fecha = NSDate.initFromString(json["Fecha"].object as? String);
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Titulo"] = self.titulo;
	
	

	
		dictionary["Cuerpo"] = self.cuerpo;
	
	

	
		dictionary["Fecha"] = self.fecha?.toString();
	
	
		
		
		
		return dictionary;
	}
}

	