//
// TipoAccionDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class TipoAccionDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var puntuacion: Int?;
	var nombre: String?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.puntuacion = json["Puntuacion"].object as? Int;
		self.nombre = json["Nombre"].object as? String;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Puntuacion"] = self.puntuacion;
	
	

	
		dictionary["Nombre"] = self.nombre;
	
	
		
		
		
		return dictionary;
	}
}

	