
package reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.enumerations;

/**
 * Code autogenerated. Do not modify this file.
 */
public enum TipoContenedor
{
	// region - Literals

	Papel (1)
	,	Cristal (2)
	,	Plastico (3)
	,	Organico (4)
;

	// endregion


	// region - Members and constructor

	private final int rawValue;

	public int getRawValue ()
	{
		return this.rawValue;
	}

	TipoContenedor (int rawValue)
	{
		this.rawValue = rawValue;
	}

	// endregion


	// region - Public methods

	public static TipoContenedor fromRawValue (int rawValue)
	{
		TipoContenedor[] enumValues = TipoContenedor.values();

		for (int i = 0; i < enumValues.length; i++)
		{
			if (enumValues[i].Compare(rawValue))
			{
				return enumValues[i];
			}
		}

		return null;
	}

	public boolean Compare (int rawValue)
	{
		return this.rawValue == rawValue;
	}

	// endregion
	
}
