	
		package reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class DudaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String titulo;
				public String getTitulo () { return titulo; } 
				public void setTitulo  (String value) { titulo = value;  } 
				    	 
				private String cuerpo;
				public String getCuerpo () { return cuerpo; } 
				public void setCuerpo  (String value) { cuerpo = value;  } 
				    	 
				private Integer usuario_oid;
				public Integer  getUsuario_oid () { return usuario_oid; } 
				public void setUsuario_oid (Integer value) { usuario_oid = value;  } 
				    	 
				private ArrayList<RespuestaDTO> respuestas;
				public ArrayList<RespuestaDTO> getRespuestas () { return respuestas; } 
				public void setRespuestas (ArrayList<RespuestaDTO> value) { respuestas = value;  } 
				    	 
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
				private Integer util;
				public Integer getUtil () { return util; } 
				public void setUtil  (Integer value) { util = value;  } 
				    	 
				private String temas;
				public String getTemas () { return temas; } 
				public void setTemas  (String value) { temas = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Titulo", this.titulo);
				
				
						  json.put("Cuerpo", this.cuerpo);
				

						if (this.usuario_oid != null)
						{
							json.put("Usuario_oid", this.usuario_oid.intValue());
						}

						if (this.respuestas != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.respuestas.size(); ++i)
							{
								jsonArray.put(this.respuestas.get(i).toJSON());
							}
							json.put("Respuestas", jsonArray);
						}
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				
				
						  json.put("Util", this.util.intValue());
				
				
						  json.put("Temas", this.temas);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	