	
		package reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class MaterialDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String nombre;
				public String getNombre () { return nombre; } 
				public void setNombre  (String value) { nombre = value;  } 
				    	 
				private TipoContenedor contenedor;
				public TipoContenedor getContenedor () { return contenedor; } 
				public void setContenedor  (TipoContenedor value) { contenedor = value;  } 
				    	 
				private ArrayList<Integer> items_oid;
				public ArrayList<Integer>  getItems_oid () { return items_oid; } 
				public void setItems_oid (ArrayList<Integer> value) { items_oid = value;  } 
				    	 
				private Estado esValido;
				public Estado getEsValido () { return esValido; } 
				public void setEsValido  (Estado value) { esValido = value;  } 
				    	 
				private Integer usuario_oid;
				public Integer  getUsuario_oid () { return usuario_oid; } 
				public void setUsuario_oid (Integer value) { usuario_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Nombre", this.nombre);
				
				
						  json.put("Contenedor", this.contenedor.getRawValue());
				

						if (this.items_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.items_oid.size(); ++i)
							{
								jsonArray.put(this.items_oid.get(i));
							}
							json.put("Items_oid", jsonArray);
						}
		
				
						  json.put("EsValido", this.esValido.getRawValue());
				

						if (this.usuario_oid != null)
						{
							json.put("Usuario_oid", this.usuario_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	