	
		package reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.utils.*;
		import  reciclaUAGenReciclaUAAdminRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class UsuarioDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String nombre;
				public String getNombre () { return nombre; } 
				public void setNombre  (String value) { nombre = value;  } 
				    	 
				private String apellidos;
				public String getApellidos () { return apellidos; } 
				public void setApellidos  (String value) { apellidos = value;  } 
				    	 
				private String email;
				public String getEmail () { return email; } 
				public void setEmail  (String value) { email = value;  } 
				    	 
				private String pass;
				public String getPass () { return pass; } 
				public void setPass  (String value) { pass = value;  } 
				    	 
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
				private ArrayList<Integer> items_oid;
				public ArrayList<Integer>  getItems_oid () { return items_oid; } 
				public void setItems_oid (ArrayList<Integer> value) { items_oid = value;  } 
				    	 
				private ArrayList<Integer> dudas_oid;
				public ArrayList<Integer>  getDudas_oid () { return dudas_oid; } 
				public void setDudas_oid (ArrayList<Integer> value) { dudas_oid = value;  } 
				    	 
				private ArrayList<Integer> respuestas_oid;
				public ArrayList<Integer>  getRespuestas_oid () { return respuestas_oid; } 
				public void setRespuestas_oid (ArrayList<Integer> value) { respuestas_oid = value;  } 
				    	 
				private ArrayList<Integer> puntos_oid;
				public ArrayList<Integer>  getPuntos_oid () { return puntos_oid; } 
				public void setPuntos_oid (ArrayList<Integer> value) { puntos_oid = value;  } 
				    	 
				private Boolean emailVerificado;
				public Boolean getEmailVerificado () { return emailVerificado; } 
				public void setEmailVerificado  (Boolean value) { emailVerificado = value;  } 
				    	 
				private ArrayList<Integer> materiales_oid;
				public ArrayList<Integer>  getMateriales_oid () { return materiales_oid; } 
				public void setMateriales_oid (ArrayList<Integer> value) { materiales_oid = value;  } 
				    	 
				private Boolean borrado;
				public Boolean getBorrado () { return borrado; } 
				public void setBorrado  (Boolean value) { borrado = value;  } 
				    	 
				private Integer juegos_oid;
				public Integer  getJuegos_oid () { return juegos_oid; } 
				public void setJuegos_oid (Integer value) { juegos_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Nombre", this.nombre);
				
				
						  json.put("Apellidos", this.apellidos);
				
				
						  json.put("Email", this.email);
				
				
						  json.put("Pass", this.pass);
				
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				

						if (this.items_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.items_oid.size(); ++i)
							{
								jsonArray.put(this.items_oid.get(i));
							}
							json.put("Items_oid", jsonArray);
						}
		

						if (this.dudas_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.dudas_oid.size(); ++i)
							{
								jsonArray.put(this.dudas_oid.get(i));
							}
							json.put("Dudas_oid", jsonArray);
						}
		

						if (this.respuestas_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.respuestas_oid.size(); ++i)
							{
								jsonArray.put(this.respuestas_oid.get(i));
							}
							json.put("Respuestas_oid", jsonArray);
						}
		

						if (this.puntos_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.puntos_oid.size(); ++i)
							{
								jsonArray.put(this.puntos_oid.get(i));
							}
							json.put("Puntos_oid", jsonArray);
						}
		
				
						  json.put("EmailVerificado", this.emailVerificado);
				

						if (this.materiales_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.materiales_oid.size(); ++i)
							{
								jsonArray.put(this.materiales_oid.get(i));
							}
							json.put("Materiales_oid", jsonArray);
						}
		
				
						  json.put("Borrado", this.borrado);
				

						if (this.juegos_oid != null)
						{
							json.put("Juegos_oid", this.juegos_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	