	
		//
		// ContenedorDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class ContenedorDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var tipo: TipoContenedor?;
				    	 
		 
				var punto_oid: Int?;
				    	 
		 
				var acciones_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["tipo"] = self.tipo?.rawValue;
				

					dictionary["punto_oid"] = self.punto_oid;
			

					dictionary["acciones_oid"] = self.acciones_oid;
			
						
				return dictionary;
			}
		}
		
	