	
		//
		// EstanciaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class EstanciaDTO 	    {
		 
				var id: String?;
				    	 
		 
				var actividad: String?;
				    	 
		 
				var latitud: Double?;
				    	 
		 
				var longitud: Double?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var edificio_oid: Int?;
				    	 
		 
				var planta_oid: Int?;
				    	 
		 
				var puntos_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["actividad"] = self.actividad;
				

				
					dictionary["latitud"] = self.latitud;
				

				
					dictionary["longitud"] = self.longitud;
				

				
					dictionary["nombre"] = self.nombre;
				

					dictionary["edificio_oid"] = self.edificio_oid;
			

					dictionary["planta_oid"] = self.planta_oid;
			

					dictionary["puntos_oid"] = self.puntos_oid;
			
						
				return dictionary;
			}
		}
		
	