	
		//
		// ItemDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class ItemDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var descripcion: String?;
				    	 
		 
				var imagen: String?;
				    	 
		 
				var esValido: Estado?;
				    	 
		 
				var usuario_oid: Int?;
				    	 
		 
				var nivel_oid: Int?;
				    	 
		 
				var material_oid: Int?;
				    	 
		 
				var accionReciclar_oid: [Int]?;
				    	 
		 
				var puntuacion: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["descripcion"] = self.descripcion;
				

				
					dictionary["imagen"] = self.imagen;
				

				
					dictionary["esValido"] = self.esValido?.rawValue;
				

					dictionary["usuario_oid"] = self.usuario_oid;
			

					dictionary["nivel_oid"] = self.nivel_oid;
			

					dictionary["material_oid"] = self.material_oid;
			

					dictionary["accionReciclar_oid"] = self.accionReciclar_oid;
			

				
					dictionary["puntuacion"] = self.puntuacion;
				
						
				return dictionary;
			}
		}
		
	