	
		//
		// MaterialDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class MaterialDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var contenedor: TipoContenedor?;
				    	 
		 
				var items_oid: [Int]?;
				    	 
		 
				var esValido: Estado?;
				    	 
		 
				var usuario_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["contenedor"] = self.contenedor?.rawValue;
				

					dictionary["items_oid"] = self.items_oid;
			

				
					dictionary["esValido"] = self.esValido?.rawValue;
				

					dictionary["usuario_oid"] = self.usuario_oid;
			
						
				return dictionary;
			}
		}
		
	