	
		//
		// UsuarioWebDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class UsuarioWebDTO :    		UsuarioDTO
	    {
		 
				var acciones: [AccionDTO]?;
				    	 
		 
				var puntuacion: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


					dictionary["acciones"] = NSNull();
					if (self.acciones != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.acciones!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["acciones"] = arrayOfDictionary;
					}
			

				
					dictionary["puntuacion"] = self.puntuacion;
				
						
				return dictionary;
			}
		}
		
	