	
		//
		// UsuarioDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class UsuarioDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var apellidos: String?;
				    	 
		 
				var email: String?;
				    	 
		 
				var pass: String?;
				    	 
		 
				var fecha: NSDate?;
				    	 
		 
				var items_oid: [Int]?;
				    	 
		 
				var dudas_oid: [Int]?;
				    	 
		 
				var respuestas_oid: [Int]?;
				    	 
		 
				var puntos_oid: [Int]?;
				    	 
		 
				var emailVerificado: Bool?;
				    	 
		 
				var materiales_oid: [Int]?;
				    	 
		 
				var borrado: Bool?;
				    	 
		 
				var juegos_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["apellidos"] = self.apellidos;
				

				
					dictionary["email"] = self.email;
				

				
					dictionary["pass"] = self.pass;
				

				
					dictionary["fecha"] = self.fecha?.toString();
				

					dictionary["items_oid"] = self.items_oid;
			

					dictionary["dudas_oid"] = self.dudas_oid;
			

					dictionary["respuestas_oid"] = self.respuestas_oid;
			

					dictionary["puntos_oid"] = self.puntos_oid;
			

				
					dictionary["emailVerificado"] = self.emailVerificado;
				

					dictionary["materiales_oid"] = self.materiales_oid;
			

				
					dictionary["borrado"] = self.borrado;
				

					dictionary["juegos_oid"] = self.juegos_oid;
			
						
				return dictionary;
			}
		}
		
	