//
// Enumerations.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation


enum TipoContenedor: Int
{
	case Papel = 1
	case Cristal = 2
	case Plastico = 3
	case Organico = 4
}

enum Planta: Int
{
	case PB = 1
	case P1 = 2
	case P2 = 3
	case P3 = 4
	case P4 = 5
	case PS = 6
}

enum Estado: Int
{
	case Verificado = 1
	case EnProceso = 2
	case Descartado = 3
}

	